#!/usr/bin/env python3
"""
Draft script: expand outline into a Markdown draft using a pro model.
Usage: draft.py --outline outline.json --model openai/gpt-4o --out draft.md
"""
import sys
import json
import argparse
import os
from pathlib import Path
from config_manager import ConfigManager
from llm_utils import call_llm

def read_json(p):
    return json.loads(Path(p).read_text(encoding='utf-8'))

def write_text(p, s):
    Path(p).write_text(s, encoding='utf-8')

def generate_draft(outline, model_name, templates_content=None):
    """
    Generate a draft using an LLM API.
    """

    title = outline.get('headlines', ["Untitled"])[0]
    points = outline.get('points', [])
    linked_docs = outline.get('linked_docs', [])
    tag_similar = outline.get('tag_similar_docs', [])

    # Construct context from linked docs
    context_str = ""
    if linked_docs:
        context_str += "## Referenced Notes\n"
        for doc in linked_docs:
            # Simple truncation to avoid blowing up context
            content_snippet = doc.get('content', '')[:1000]
            context_str += f"### Note: {Path(doc.get('path', 'unknown')).stem}\n{content_snippet}\n...\n\n"

    if tag_similar:
        context_str += "## Related Ideas (Context)\n"
        for doc in tag_similar:
            content_snippet = doc.get('content', '')[:500]
            context_str += f"### Note: {Path(doc.get('path', 'unknown')).stem}\n{content_snippet}\n...\n\n"

    # Construct system prompt
    system_prompt = "You are an expert writer and researcher."
    if templates_content:
        system_prompt += f"\n\nUse the following templates and style guide:\n{templates_content}"

    system_prompt += """\n\nIMPORTANT: Focus on the core idea presented in the outline.
Filter out irrelevant or tangential information from the context notes.
It is okay to not include everything. Your goal is a coherent, focused draft."""

    # Construct user prompt
    user_prompt = f"""
    Please write a comprehensive draft based on the following outline and context.

    # Title: {title}

    # Key Points to Cover:
    {json.dumps(points, indent=2)}

    # Context Material:
    {context_str}

    Output Format: Markdown.
    """

    response = call_llm(system_prompt, user_prompt, model_name)

    if response:
        return response
    else:
        print("Warning: LLM call failed or no API Key. Outputting prompt for manual use.\n", file=sys.stderr)
        return f"# PROMPT FOR AGENT\n\n**System**:\n{system_prompt}\n\n**User**:\n{user_prompt}"

if __name__ == '__main__':
    # Load configuration
    config = ConfigManager.load()
    default_model = config.get('pro_model', 'openai/gpt-4o')

    p = argparse.ArgumentParser()
    p.add_argument('--outline', required=True)
    p.add_argument('--model', default=default_model)
    p.add_argument('--out', required=True)
    p.add_argument('--templates', help="Path to templates.md", default="references/templates.md")
    args = p.parse_args()

    outline = read_json(args.outline)

    templates_content = None
    if args.templates and Path(args.templates).exists():
        templates_content = Path(args.templates).read_text(encoding='utf-8')

    draft_md = generate_draft(outline, args.model, templates_content)

    # Add metadata footer
    draft_md += f"\n\n---\n*Generated by writing-brainstormer (model: {args.model})*"

    write_text(args.out, draft_md)
    print(f'Wrote draft to {args.out}')
