#!/usr/bin/env python3
"""
Draft script: expand outline into a Markdown draft using a pro model.
Usage: draft.py --outline outline.json --model openai/gpt-5.2 --out draft.md
"""
import sys, json, argparse
from pathlib import Path
from config_manager import ConfigManager

def read_json(p):
    return json.loads(Path(p).read_text(encoding='utf-8'))

def write_text(p, s):
    Path(p).write_text(s, encoding='utf-8')

if __name__ == '__main__':
    # Load configuration
    config = ConfigManager.load()
    default_model = config.get('pro_model', 'openai/gpt-5.2')

    p = argparse.ArgumentParser()
    p.add_argument('--outline', required=True)
    p.add_argument('--model', default=default_model)
    p.add_argument('--out', required=True)
    args = p.parse_args()

    outline = read_json(args.outline)

    # Placeholder expansion logic: create a simple markdown from the outline.
    title = outline.get('headlines',["Untitled"])[0]
    points = outline.get('points',[])

    md = f"# {title}\n\n"
    md += "Generated Draft\n\n"
    md += "## Key Points\n\n"
    for i,pnt in enumerate(points,1):
        md += f"{i}. {pnt}\n\n"

    md += "---\n\n" + "*Generated by writing-brainstormer (preprocessed with kimi-k2.5; draft model: %s)*\n" % args.model

    write_text(args.out, md)
    print('Wrote', args.out)
